// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LieDice.proto

package com.orange.network.game.protocol.model;

public final class LieDiceProtos {
  private LieDiceProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface DiceOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional int32 diceId = 1;
    boolean hasDiceId();
    int getDiceId();
    
    // required int32 dice = 2;
    boolean hasDice();
    int getDice();
  }
  public static final class Dice extends
      com.google.protobuf.GeneratedMessage
      implements DiceOrBuilder {
    // Use Dice.newBuilder() to construct.
    private Dice(Builder builder) {
      super(builder);
    }
    private Dice(boolean noInit) {}
    
    private static final Dice defaultInstance;
    public static Dice getDefaultInstance() {
      return defaultInstance;
    }
    
    public Dice getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.orange.network.game.protocol.model.LieDiceProtos.internal_static_game_Dice_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.orange.network.game.protocol.model.LieDiceProtos.internal_static_game_Dice_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional int32 diceId = 1;
    public static final int DICEID_FIELD_NUMBER = 1;
    private int diceId_;
    public boolean hasDiceId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getDiceId() {
      return diceId_;
    }
    
    // required int32 dice = 2;
    public static final int DICE_FIELD_NUMBER = 2;
    private int dice_;
    public boolean hasDice() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getDice() {
      return dice_;
    }
    
    private void initFields() {
      diceId_ = 0;
      dice_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasDice()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, diceId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, dice_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, diceId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, dice_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.orange.network.game.protocol.model.LieDiceProtos.Dice parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.orange.network.game.protocol.model.LieDiceProtos.Dice parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.orange.network.game.protocol.model.LieDiceProtos.Dice parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.orange.network.game.protocol.model.LieDiceProtos.Dice parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.orange.network.game.protocol.model.LieDiceProtos.Dice parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.orange.network.game.protocol.model.LieDiceProtos.Dice parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.orange.network.game.protocol.model.LieDiceProtos.Dice parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.orange.network.game.protocol.model.LieDiceProtos.Dice parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.orange.network.game.protocol.model.LieDiceProtos.Dice parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.orange.network.game.protocol.model.LieDiceProtos.Dice parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.orange.network.game.protocol.model.LieDiceProtos.Dice prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.orange.network.game.protocol.model.LieDiceProtos.DiceOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.orange.network.game.protocol.model.LieDiceProtos.internal_static_game_Dice_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.orange.network.game.protocol.model.LieDiceProtos.internal_static_game_Dice_fieldAccessorTable;
      }
      
      // Construct using com.orange.network.game.protocol.model.LieDiceProtos.Dice.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        diceId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        dice_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.orange.network.game.protocol.model.LieDiceProtos.Dice.getDescriptor();
      }
      
      public com.orange.network.game.protocol.model.LieDiceProtos.Dice getDefaultInstanceForType() {
        return com.orange.network.game.protocol.model.LieDiceProtos.Dice.getDefaultInstance();
      }
      
      public com.orange.network.game.protocol.model.LieDiceProtos.Dice build() {
        com.orange.network.game.protocol.model.LieDiceProtos.Dice result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.orange.network.game.protocol.model.LieDiceProtos.Dice buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.orange.network.game.protocol.model.LieDiceProtos.Dice result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.orange.network.game.protocol.model.LieDiceProtos.Dice buildPartial() {
        com.orange.network.game.protocol.model.LieDiceProtos.Dice result = new com.orange.network.game.protocol.model.LieDiceProtos.Dice(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.diceId_ = diceId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.dice_ = dice_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.orange.network.game.protocol.model.LieDiceProtos.Dice) {
          return mergeFrom((com.orange.network.game.protocol.model.LieDiceProtos.Dice)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.orange.network.game.protocol.model.LieDiceProtos.Dice other) {
        if (other == com.orange.network.game.protocol.model.LieDiceProtos.Dice.getDefaultInstance()) return this;
        if (other.hasDiceId()) {
          setDiceId(other.getDiceId());
        }
        if (other.hasDice()) {
          setDice(other.getDice());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasDice()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              diceId_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              dice_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional int32 diceId = 1;
      private int diceId_ ;
      public boolean hasDiceId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getDiceId() {
        return diceId_;
      }
      public Builder setDiceId(int value) {
        bitField0_ |= 0x00000001;
        diceId_ = value;
        onChanged();
        return this;
      }
      public Builder clearDiceId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        diceId_ = 0;
        onChanged();
        return this;
      }
      
      // required int32 dice = 2;
      private int dice_ ;
      public boolean hasDice() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getDice() {
        return dice_;
      }
      public Builder setDice(int value) {
        bitField0_ |= 0x00000002;
        dice_ = value;
        onChanged();
        return this;
      }
      public Builder clearDice() {
        bitField0_ = (bitField0_ & ~0x00000002);
        dice_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:game.Dice)
    }
    
    static {
      defaultInstance = new Dice(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:game.Dice)
  }
  
  public interface UserDiceOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 userId = 1;
    boolean hasUserId();
    int getUserId();
    
    // repeated .game.Dice dices = 2;
    java.util.List<com.orange.network.game.protocol.model.LieDiceProtos.Dice> 
        getDicesList();
    com.orange.network.game.protocol.model.LieDiceProtos.Dice getDices(int index);
    int getDicesCount();
    java.util.List<? extends com.orange.network.game.protocol.model.LieDiceProtos.DiceOrBuilder> 
        getDicesOrBuilderList();
    com.orange.network.game.protocol.model.LieDiceProtos.DiceOrBuilder getDicesOrBuilder(
        int index);
  }
  public static final class UserDice extends
      com.google.protobuf.GeneratedMessage
      implements UserDiceOrBuilder {
    // Use UserDice.newBuilder() to construct.
    private UserDice(Builder builder) {
      super(builder);
    }
    private UserDice(boolean noInit) {}
    
    private static final UserDice defaultInstance;
    public static UserDice getDefaultInstance() {
      return defaultInstance;
    }
    
    public UserDice getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.orange.network.game.protocol.model.LieDiceProtos.internal_static_game_UserDice_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.orange.network.game.protocol.model.LieDiceProtos.internal_static_game_UserDice_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 userId = 1;
    public static final int USERID_FIELD_NUMBER = 1;
    private int userId_;
    public boolean hasUserId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getUserId() {
      return userId_;
    }
    
    // repeated .game.Dice dices = 2;
    public static final int DICES_FIELD_NUMBER = 2;
    private java.util.List<com.orange.network.game.protocol.model.LieDiceProtos.Dice> dices_;
    public java.util.List<com.orange.network.game.protocol.model.LieDiceProtos.Dice> getDicesList() {
      return dices_;
    }
    public java.util.List<? extends com.orange.network.game.protocol.model.LieDiceProtos.DiceOrBuilder> 
        getDicesOrBuilderList() {
      return dices_;
    }
    public int getDicesCount() {
      return dices_.size();
    }
    public com.orange.network.game.protocol.model.LieDiceProtos.Dice getDices(int index) {
      return dices_.get(index);
    }
    public com.orange.network.game.protocol.model.LieDiceProtos.DiceOrBuilder getDicesOrBuilder(
        int index) {
      return dices_.get(index);
    }
    
    private void initFields() {
      userId_ = 0;
      dices_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasUserId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getDicesCount(); i++) {
        if (!getDices(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, userId_);
      }
      for (int i = 0; i < dices_.size(); i++) {
        output.writeMessage(2, dices_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, userId_);
      }
      for (int i = 0; i < dices_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, dices_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.orange.network.game.protocol.model.LieDiceProtos.UserDice parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.orange.network.game.protocol.model.LieDiceProtos.UserDice parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.orange.network.game.protocol.model.LieDiceProtos.UserDice parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.orange.network.game.protocol.model.LieDiceProtos.UserDice parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.orange.network.game.protocol.model.LieDiceProtos.UserDice parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.orange.network.game.protocol.model.LieDiceProtos.UserDice parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.orange.network.game.protocol.model.LieDiceProtos.UserDice parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.orange.network.game.protocol.model.LieDiceProtos.UserDice parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.orange.network.game.protocol.model.LieDiceProtos.UserDice parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.orange.network.game.protocol.model.LieDiceProtos.UserDice parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.orange.network.game.protocol.model.LieDiceProtos.UserDice prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.orange.network.game.protocol.model.LieDiceProtos.UserDiceOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.orange.network.game.protocol.model.LieDiceProtos.internal_static_game_UserDice_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.orange.network.game.protocol.model.LieDiceProtos.internal_static_game_UserDice_fieldAccessorTable;
      }
      
      // Construct using com.orange.network.game.protocol.model.LieDiceProtos.UserDice.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getDicesFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        userId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (dicesBuilder_ == null) {
          dices_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          dicesBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.orange.network.game.protocol.model.LieDiceProtos.UserDice.getDescriptor();
      }
      
      public com.orange.network.game.protocol.model.LieDiceProtos.UserDice getDefaultInstanceForType() {
        return com.orange.network.game.protocol.model.LieDiceProtos.UserDice.getDefaultInstance();
      }
      
      public com.orange.network.game.protocol.model.LieDiceProtos.UserDice build() {
        com.orange.network.game.protocol.model.LieDiceProtos.UserDice result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.orange.network.game.protocol.model.LieDiceProtos.UserDice buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.orange.network.game.protocol.model.LieDiceProtos.UserDice result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.orange.network.game.protocol.model.LieDiceProtos.UserDice buildPartial() {
        com.orange.network.game.protocol.model.LieDiceProtos.UserDice result = new com.orange.network.game.protocol.model.LieDiceProtos.UserDice(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.userId_ = userId_;
        if (dicesBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            dices_ = java.util.Collections.unmodifiableList(dices_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.dices_ = dices_;
        } else {
          result.dices_ = dicesBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.orange.network.game.protocol.model.LieDiceProtos.UserDice) {
          return mergeFrom((com.orange.network.game.protocol.model.LieDiceProtos.UserDice)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.orange.network.game.protocol.model.LieDiceProtos.UserDice other) {
        if (other == com.orange.network.game.protocol.model.LieDiceProtos.UserDice.getDefaultInstance()) return this;
        if (other.hasUserId()) {
          setUserId(other.getUserId());
        }
        if (dicesBuilder_ == null) {
          if (!other.dices_.isEmpty()) {
            if (dices_.isEmpty()) {
              dices_ = other.dices_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureDicesIsMutable();
              dices_.addAll(other.dices_);
            }
            onChanged();
          }
        } else {
          if (!other.dices_.isEmpty()) {
            if (dicesBuilder_.isEmpty()) {
              dicesBuilder_.dispose();
              dicesBuilder_ = null;
              dices_ = other.dices_;
              bitField0_ = (bitField0_ & ~0x00000002);
              dicesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getDicesFieldBuilder() : null;
            } else {
              dicesBuilder_.addAllMessages(other.dices_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasUserId()) {
          
          return false;
        }
        for (int i = 0; i < getDicesCount(); i++) {
          if (!getDices(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              userId_ = input.readInt32();
              break;
            }
            case 18: {
              com.orange.network.game.protocol.model.LieDiceProtos.Dice.Builder subBuilder = com.orange.network.game.protocol.model.LieDiceProtos.Dice.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addDices(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 userId = 1;
      private int userId_ ;
      public boolean hasUserId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getUserId() {
        return userId_;
      }
      public Builder setUserId(int value) {
        bitField0_ |= 0x00000001;
        userId_ = value;
        onChanged();
        return this;
      }
      public Builder clearUserId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        userId_ = 0;
        onChanged();
        return this;
      }
      
      // repeated .game.Dice dices = 2;
      private java.util.List<com.orange.network.game.protocol.model.LieDiceProtos.Dice> dices_ =
        java.util.Collections.emptyList();
      private void ensureDicesIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          dices_ = new java.util.ArrayList<com.orange.network.game.protocol.model.LieDiceProtos.Dice>(dices_);
          bitField0_ |= 0x00000002;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          com.orange.network.game.protocol.model.LieDiceProtos.Dice, com.orange.network.game.protocol.model.LieDiceProtos.Dice.Builder, com.orange.network.game.protocol.model.LieDiceProtos.DiceOrBuilder> dicesBuilder_;
      
      public java.util.List<com.orange.network.game.protocol.model.LieDiceProtos.Dice> getDicesList() {
        if (dicesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(dices_);
        } else {
          return dicesBuilder_.getMessageList();
        }
      }
      public int getDicesCount() {
        if (dicesBuilder_ == null) {
          return dices_.size();
        } else {
          return dicesBuilder_.getCount();
        }
      }
      public com.orange.network.game.protocol.model.LieDiceProtos.Dice getDices(int index) {
        if (dicesBuilder_ == null) {
          return dices_.get(index);
        } else {
          return dicesBuilder_.getMessage(index);
        }
      }
      public Builder setDices(
          int index, com.orange.network.game.protocol.model.LieDiceProtos.Dice value) {
        if (dicesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDicesIsMutable();
          dices_.set(index, value);
          onChanged();
        } else {
          dicesBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setDices(
          int index, com.orange.network.game.protocol.model.LieDiceProtos.Dice.Builder builderForValue) {
        if (dicesBuilder_ == null) {
          ensureDicesIsMutable();
          dices_.set(index, builderForValue.build());
          onChanged();
        } else {
          dicesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addDices(com.orange.network.game.protocol.model.LieDiceProtos.Dice value) {
        if (dicesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDicesIsMutable();
          dices_.add(value);
          onChanged();
        } else {
          dicesBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addDices(
          int index, com.orange.network.game.protocol.model.LieDiceProtos.Dice value) {
        if (dicesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDicesIsMutable();
          dices_.add(index, value);
          onChanged();
        } else {
          dicesBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addDices(
          com.orange.network.game.protocol.model.LieDiceProtos.Dice.Builder builderForValue) {
        if (dicesBuilder_ == null) {
          ensureDicesIsMutable();
          dices_.add(builderForValue.build());
          onChanged();
        } else {
          dicesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addDices(
          int index, com.orange.network.game.protocol.model.LieDiceProtos.Dice.Builder builderForValue) {
        if (dicesBuilder_ == null) {
          ensureDicesIsMutable();
          dices_.add(index, builderForValue.build());
          onChanged();
        } else {
          dicesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllDices(
          java.lang.Iterable<? extends com.orange.network.game.protocol.model.LieDiceProtos.Dice> values) {
        if (dicesBuilder_ == null) {
          ensureDicesIsMutable();
          super.addAll(values, dices_);
          onChanged();
        } else {
          dicesBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearDices() {
        if (dicesBuilder_ == null) {
          dices_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          dicesBuilder_.clear();
        }
        return this;
      }
      public Builder removeDices(int index) {
        if (dicesBuilder_ == null) {
          ensureDicesIsMutable();
          dices_.remove(index);
          onChanged();
        } else {
          dicesBuilder_.remove(index);
        }
        return this;
      }
      public com.orange.network.game.protocol.model.LieDiceProtos.Dice.Builder getDicesBuilder(
          int index) {
        return getDicesFieldBuilder().getBuilder(index);
      }
      public com.orange.network.game.protocol.model.LieDiceProtos.DiceOrBuilder getDicesOrBuilder(
          int index) {
        if (dicesBuilder_ == null) {
          return dices_.get(index);  } else {
          return dicesBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends com.orange.network.game.protocol.model.LieDiceProtos.DiceOrBuilder> 
           getDicesOrBuilderList() {
        if (dicesBuilder_ != null) {
          return dicesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(dices_);
        }
      }
      public com.orange.network.game.protocol.model.LieDiceProtos.Dice.Builder addDicesBuilder() {
        return getDicesFieldBuilder().addBuilder(
            com.orange.network.game.protocol.model.LieDiceProtos.Dice.getDefaultInstance());
      }
      public com.orange.network.game.protocol.model.LieDiceProtos.Dice.Builder addDicesBuilder(
          int index) {
        return getDicesFieldBuilder().addBuilder(
            index, com.orange.network.game.protocol.model.LieDiceProtos.Dice.getDefaultInstance());
      }
      public java.util.List<com.orange.network.game.protocol.model.LieDiceProtos.Dice.Builder> 
           getDicesBuilderList() {
        return getDicesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.orange.network.game.protocol.model.LieDiceProtos.Dice, com.orange.network.game.protocol.model.LieDiceProtos.Dice.Builder, com.orange.network.game.protocol.model.LieDiceProtos.DiceOrBuilder> 
          getDicesFieldBuilder() {
        if (dicesBuilder_ == null) {
          dicesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.orange.network.game.protocol.model.LieDiceProtos.Dice, com.orange.network.game.protocol.model.LieDiceProtos.Dice.Builder, com.orange.network.game.protocol.model.LieDiceProtos.DiceOrBuilder>(
                  dices_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          dices_ = null;
        }
        return dicesBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:game.UserDice)
    }
    
    static {
      defaultInstance = new UserDice(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:game.UserDice)
  }
  
  public interface UserResultOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string userId = 1;
    boolean hasUserId();
    String getUserId();
    
    // required bool win = 2;
    boolean hasWin();
    boolean getWin();
    
    // required int32 gainCoins = 5;
    boolean hasGainCoins();
    int getGainCoins();
  }
  public static final class UserResult extends
      com.google.protobuf.GeneratedMessage
      implements UserResultOrBuilder {
    // Use UserResult.newBuilder() to construct.
    private UserResult(Builder builder) {
      super(builder);
    }
    private UserResult(boolean noInit) {}
    
    private static final UserResult defaultInstance;
    public static UserResult getDefaultInstance() {
      return defaultInstance;
    }
    
    public UserResult getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.orange.network.game.protocol.model.LieDiceProtos.internal_static_game_UserResult_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.orange.network.game.protocol.model.LieDiceProtos.internal_static_game_UserResult_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string userId = 1;
    public static final int USERID_FIELD_NUMBER = 1;
    private java.lang.Object userId_;
    public boolean hasUserId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getUserId() {
      java.lang.Object ref = userId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          userId_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getUserIdBytes() {
      java.lang.Object ref = userId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required bool win = 2;
    public static final int WIN_FIELD_NUMBER = 2;
    private boolean win_;
    public boolean hasWin() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public boolean getWin() {
      return win_;
    }
    
    // required int32 gainCoins = 5;
    public static final int GAINCOINS_FIELD_NUMBER = 5;
    private int gainCoins_;
    public boolean hasGainCoins() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getGainCoins() {
      return gainCoins_;
    }
    
    private void initFields() {
      userId_ = "";
      win_ = false;
      gainCoins_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasUserId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasWin()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasGainCoins()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getUserIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBool(2, win_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(5, gainCoins_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getUserIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, win_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, gainCoins_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.orange.network.game.protocol.model.LieDiceProtos.UserResult parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.orange.network.game.protocol.model.LieDiceProtos.UserResult parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.orange.network.game.protocol.model.LieDiceProtos.UserResult parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.orange.network.game.protocol.model.LieDiceProtos.UserResult parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.orange.network.game.protocol.model.LieDiceProtos.UserResult parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.orange.network.game.protocol.model.LieDiceProtos.UserResult parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.orange.network.game.protocol.model.LieDiceProtos.UserResult parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.orange.network.game.protocol.model.LieDiceProtos.UserResult parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.orange.network.game.protocol.model.LieDiceProtos.UserResult parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.orange.network.game.protocol.model.LieDiceProtos.UserResult parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.orange.network.game.protocol.model.LieDiceProtos.UserResult prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.orange.network.game.protocol.model.LieDiceProtos.UserResultOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.orange.network.game.protocol.model.LieDiceProtos.internal_static_game_UserResult_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.orange.network.game.protocol.model.LieDiceProtos.internal_static_game_UserResult_fieldAccessorTable;
      }
      
      // Construct using com.orange.network.game.protocol.model.LieDiceProtos.UserResult.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        userId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        win_ = false;
        bitField0_ = (bitField0_ & ~0x00000002);
        gainCoins_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.orange.network.game.protocol.model.LieDiceProtos.UserResult.getDescriptor();
      }
      
      public com.orange.network.game.protocol.model.LieDiceProtos.UserResult getDefaultInstanceForType() {
        return com.orange.network.game.protocol.model.LieDiceProtos.UserResult.getDefaultInstance();
      }
      
      public com.orange.network.game.protocol.model.LieDiceProtos.UserResult build() {
        com.orange.network.game.protocol.model.LieDiceProtos.UserResult result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.orange.network.game.protocol.model.LieDiceProtos.UserResult buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.orange.network.game.protocol.model.LieDiceProtos.UserResult result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.orange.network.game.protocol.model.LieDiceProtos.UserResult buildPartial() {
        com.orange.network.game.protocol.model.LieDiceProtos.UserResult result = new com.orange.network.game.protocol.model.LieDiceProtos.UserResult(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.userId_ = userId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.win_ = win_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.gainCoins_ = gainCoins_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.orange.network.game.protocol.model.LieDiceProtos.UserResult) {
          return mergeFrom((com.orange.network.game.protocol.model.LieDiceProtos.UserResult)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.orange.network.game.protocol.model.LieDiceProtos.UserResult other) {
        if (other == com.orange.network.game.protocol.model.LieDiceProtos.UserResult.getDefaultInstance()) return this;
        if (other.hasUserId()) {
          setUserId(other.getUserId());
        }
        if (other.hasWin()) {
          setWin(other.getWin());
        }
        if (other.hasGainCoins()) {
          setGainCoins(other.getGainCoins());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasUserId()) {
          
          return false;
        }
        if (!hasWin()) {
          
          return false;
        }
        if (!hasGainCoins()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              userId_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              win_ = input.readBool();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000004;
              gainCoins_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string userId = 1;
      private java.lang.Object userId_ = "";
      public boolean hasUserId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getUserId() {
        java.lang.Object ref = userId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          userId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setUserId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        userId_ = value;
        onChanged();
        return this;
      }
      public Builder clearUserId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        userId_ = getDefaultInstance().getUserId();
        onChanged();
        return this;
      }
      void setUserId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        userId_ = value;
        onChanged();
      }
      
      // required bool win = 2;
      private boolean win_ ;
      public boolean hasWin() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public boolean getWin() {
        return win_;
      }
      public Builder setWin(boolean value) {
        bitField0_ |= 0x00000002;
        win_ = value;
        onChanged();
        return this;
      }
      public Builder clearWin() {
        bitField0_ = (bitField0_ & ~0x00000002);
        win_ = false;
        onChanged();
        return this;
      }
      
      // required int32 gainCoins = 5;
      private int gainCoins_ ;
      public boolean hasGainCoins() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getGainCoins() {
        return gainCoins_;
      }
      public Builder setGainCoins(int value) {
        bitField0_ |= 0x00000004;
        gainCoins_ = value;
        onChanged();
        return this;
      }
      public Builder clearGainCoins() {
        bitField0_ = (bitField0_ & ~0x00000004);
        gainCoins_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:game.UserResult)
    }
    
    static {
      defaultInstance = new UserResult(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:game.UserResult)
  }
  
  public interface LieDiceGameResultOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required .game.UserResult openDiceUserResult = 1;
    boolean hasOpenDiceUserResult();
    com.orange.network.game.protocol.model.LieDiceProtos.UserResult getOpenDiceUserResult();
    com.orange.network.game.protocol.model.LieDiceProtos.UserResultOrBuilder getOpenDiceUserResultOrBuilder();
    
    // required .game.UserResult callDiceUserResult = 2;
    boolean hasCallDiceUserResult();
    com.orange.network.game.protocol.model.LieDiceProtos.UserResult getCallDiceUserResult();
    com.orange.network.game.protocol.model.LieDiceProtos.UserResultOrBuilder getCallDiceUserResultOrBuilder();
    
    // optional int32 openType = 5 [default = 0];
    boolean hasOpenType();
    int getOpenType();
  }
  public static final class LieDiceGameResult extends
      com.google.protobuf.GeneratedMessage
      implements LieDiceGameResultOrBuilder {
    // Use LieDiceGameResult.newBuilder() to construct.
    private LieDiceGameResult(Builder builder) {
      super(builder);
    }
    private LieDiceGameResult(boolean noInit) {}
    
    private static final LieDiceGameResult defaultInstance;
    public static LieDiceGameResult getDefaultInstance() {
      return defaultInstance;
    }
    
    public LieDiceGameResult getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.orange.network.game.protocol.model.LieDiceProtos.internal_static_game_LieDiceGameResult_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.orange.network.game.protocol.model.LieDiceProtos.internal_static_game_LieDiceGameResult_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required .game.UserResult openDiceUserResult = 1;
    public static final int OPENDICEUSERRESULT_FIELD_NUMBER = 1;
    private com.orange.network.game.protocol.model.LieDiceProtos.UserResult openDiceUserResult_;
    public boolean hasOpenDiceUserResult() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public com.orange.network.game.protocol.model.LieDiceProtos.UserResult getOpenDiceUserResult() {
      return openDiceUserResult_;
    }
    public com.orange.network.game.protocol.model.LieDiceProtos.UserResultOrBuilder getOpenDiceUserResultOrBuilder() {
      return openDiceUserResult_;
    }
    
    // required .game.UserResult callDiceUserResult = 2;
    public static final int CALLDICEUSERRESULT_FIELD_NUMBER = 2;
    private com.orange.network.game.protocol.model.LieDiceProtos.UserResult callDiceUserResult_;
    public boolean hasCallDiceUserResult() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public com.orange.network.game.protocol.model.LieDiceProtos.UserResult getCallDiceUserResult() {
      return callDiceUserResult_;
    }
    public com.orange.network.game.protocol.model.LieDiceProtos.UserResultOrBuilder getCallDiceUserResultOrBuilder() {
      return callDiceUserResult_;
    }
    
    // optional int32 openType = 5 [default = 0];
    public static final int OPENTYPE_FIELD_NUMBER = 5;
    private int openType_;
    public boolean hasOpenType() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getOpenType() {
      return openType_;
    }
    
    private void initFields() {
      openDiceUserResult_ = com.orange.network.game.protocol.model.LieDiceProtos.UserResult.getDefaultInstance();
      callDiceUserResult_ = com.orange.network.game.protocol.model.LieDiceProtos.UserResult.getDefaultInstance();
      openType_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasOpenDiceUserResult()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCallDiceUserResult()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getOpenDiceUserResult().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getCallDiceUserResult().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, openDiceUserResult_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, callDiceUserResult_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(5, openType_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, openDiceUserResult_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, callDiceUserResult_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, openType_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.orange.network.game.protocol.model.LieDiceProtos.LieDiceGameResult parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.orange.network.game.protocol.model.LieDiceProtos.LieDiceGameResult parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.orange.network.game.protocol.model.LieDiceProtos.LieDiceGameResult parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.orange.network.game.protocol.model.LieDiceProtos.LieDiceGameResult parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.orange.network.game.protocol.model.LieDiceProtos.LieDiceGameResult parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.orange.network.game.protocol.model.LieDiceProtos.LieDiceGameResult parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.orange.network.game.protocol.model.LieDiceProtos.LieDiceGameResult parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.orange.network.game.protocol.model.LieDiceProtos.LieDiceGameResult parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.orange.network.game.protocol.model.LieDiceProtos.LieDiceGameResult parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.orange.network.game.protocol.model.LieDiceProtos.LieDiceGameResult parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.orange.network.game.protocol.model.LieDiceProtos.LieDiceGameResult prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.orange.network.game.protocol.model.LieDiceProtos.LieDiceGameResultOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.orange.network.game.protocol.model.LieDiceProtos.internal_static_game_LieDiceGameResult_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.orange.network.game.protocol.model.LieDiceProtos.internal_static_game_LieDiceGameResult_fieldAccessorTable;
      }
      
      // Construct using com.orange.network.game.protocol.model.LieDiceProtos.LieDiceGameResult.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getOpenDiceUserResultFieldBuilder();
          getCallDiceUserResultFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (openDiceUserResultBuilder_ == null) {
          openDiceUserResult_ = com.orange.network.game.protocol.model.LieDiceProtos.UserResult.getDefaultInstance();
        } else {
          openDiceUserResultBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        if (callDiceUserResultBuilder_ == null) {
          callDiceUserResult_ = com.orange.network.game.protocol.model.LieDiceProtos.UserResult.getDefaultInstance();
        } else {
          callDiceUserResultBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        openType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.orange.network.game.protocol.model.LieDiceProtos.LieDiceGameResult.getDescriptor();
      }
      
      public com.orange.network.game.protocol.model.LieDiceProtos.LieDiceGameResult getDefaultInstanceForType() {
        return com.orange.network.game.protocol.model.LieDiceProtos.LieDiceGameResult.getDefaultInstance();
      }
      
      public com.orange.network.game.protocol.model.LieDiceProtos.LieDiceGameResult build() {
        com.orange.network.game.protocol.model.LieDiceProtos.LieDiceGameResult result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.orange.network.game.protocol.model.LieDiceProtos.LieDiceGameResult buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.orange.network.game.protocol.model.LieDiceProtos.LieDiceGameResult result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.orange.network.game.protocol.model.LieDiceProtos.LieDiceGameResult buildPartial() {
        com.orange.network.game.protocol.model.LieDiceProtos.LieDiceGameResult result = new com.orange.network.game.protocol.model.LieDiceProtos.LieDiceGameResult(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (openDiceUserResultBuilder_ == null) {
          result.openDiceUserResult_ = openDiceUserResult_;
        } else {
          result.openDiceUserResult_ = openDiceUserResultBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (callDiceUserResultBuilder_ == null) {
          result.callDiceUserResult_ = callDiceUserResult_;
        } else {
          result.callDiceUserResult_ = callDiceUserResultBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.openType_ = openType_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.orange.network.game.protocol.model.LieDiceProtos.LieDiceGameResult) {
          return mergeFrom((com.orange.network.game.protocol.model.LieDiceProtos.LieDiceGameResult)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.orange.network.game.protocol.model.LieDiceProtos.LieDiceGameResult other) {
        if (other == com.orange.network.game.protocol.model.LieDiceProtos.LieDiceGameResult.getDefaultInstance()) return this;
        if (other.hasOpenDiceUserResult()) {
          mergeOpenDiceUserResult(other.getOpenDiceUserResult());
        }
        if (other.hasCallDiceUserResult()) {
          mergeCallDiceUserResult(other.getCallDiceUserResult());
        }
        if (other.hasOpenType()) {
          setOpenType(other.getOpenType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasOpenDiceUserResult()) {
          
          return false;
        }
        if (!hasCallDiceUserResult()) {
          
          return false;
        }
        if (!getOpenDiceUserResult().isInitialized()) {
          
          return false;
        }
        if (!getCallDiceUserResult().isInitialized()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              com.orange.network.game.protocol.model.LieDiceProtos.UserResult.Builder subBuilder = com.orange.network.game.protocol.model.LieDiceProtos.UserResult.newBuilder();
              if (hasOpenDiceUserResult()) {
                subBuilder.mergeFrom(getOpenDiceUserResult());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setOpenDiceUserResult(subBuilder.buildPartial());
              break;
            }
            case 18: {
              com.orange.network.game.protocol.model.LieDiceProtos.UserResult.Builder subBuilder = com.orange.network.game.protocol.model.LieDiceProtos.UserResult.newBuilder();
              if (hasCallDiceUserResult()) {
                subBuilder.mergeFrom(getCallDiceUserResult());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setCallDiceUserResult(subBuilder.buildPartial());
              break;
            }
            case 40: {
              bitField0_ |= 0x00000004;
              openType_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .game.UserResult openDiceUserResult = 1;
      private com.orange.network.game.protocol.model.LieDiceProtos.UserResult openDiceUserResult_ = com.orange.network.game.protocol.model.LieDiceProtos.UserResult.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.orange.network.game.protocol.model.LieDiceProtos.UserResult, com.orange.network.game.protocol.model.LieDiceProtos.UserResult.Builder, com.orange.network.game.protocol.model.LieDiceProtos.UserResultOrBuilder> openDiceUserResultBuilder_;
      public boolean hasOpenDiceUserResult() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public com.orange.network.game.protocol.model.LieDiceProtos.UserResult getOpenDiceUserResult() {
        if (openDiceUserResultBuilder_ == null) {
          return openDiceUserResult_;
        } else {
          return openDiceUserResultBuilder_.getMessage();
        }
      }
      public Builder setOpenDiceUserResult(com.orange.network.game.protocol.model.LieDiceProtos.UserResult value) {
        if (openDiceUserResultBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          openDiceUserResult_ = value;
          onChanged();
        } else {
          openDiceUserResultBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder setOpenDiceUserResult(
          com.orange.network.game.protocol.model.LieDiceProtos.UserResult.Builder builderForValue) {
        if (openDiceUserResultBuilder_ == null) {
          openDiceUserResult_ = builderForValue.build();
          onChanged();
        } else {
          openDiceUserResultBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder mergeOpenDiceUserResult(com.orange.network.game.protocol.model.LieDiceProtos.UserResult value) {
        if (openDiceUserResultBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              openDiceUserResult_ != com.orange.network.game.protocol.model.LieDiceProtos.UserResult.getDefaultInstance()) {
            openDiceUserResult_ =
              com.orange.network.game.protocol.model.LieDiceProtos.UserResult.newBuilder(openDiceUserResult_).mergeFrom(value).buildPartial();
          } else {
            openDiceUserResult_ = value;
          }
          onChanged();
        } else {
          openDiceUserResultBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder clearOpenDiceUserResult() {
        if (openDiceUserResultBuilder_ == null) {
          openDiceUserResult_ = com.orange.network.game.protocol.model.LieDiceProtos.UserResult.getDefaultInstance();
          onChanged();
        } else {
          openDiceUserResultBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      public com.orange.network.game.protocol.model.LieDiceProtos.UserResult.Builder getOpenDiceUserResultBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getOpenDiceUserResultFieldBuilder().getBuilder();
      }
      public com.orange.network.game.protocol.model.LieDiceProtos.UserResultOrBuilder getOpenDiceUserResultOrBuilder() {
        if (openDiceUserResultBuilder_ != null) {
          return openDiceUserResultBuilder_.getMessageOrBuilder();
        } else {
          return openDiceUserResult_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          com.orange.network.game.protocol.model.LieDiceProtos.UserResult, com.orange.network.game.protocol.model.LieDiceProtos.UserResult.Builder, com.orange.network.game.protocol.model.LieDiceProtos.UserResultOrBuilder> 
          getOpenDiceUserResultFieldBuilder() {
        if (openDiceUserResultBuilder_ == null) {
          openDiceUserResultBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.orange.network.game.protocol.model.LieDiceProtos.UserResult, com.orange.network.game.protocol.model.LieDiceProtos.UserResult.Builder, com.orange.network.game.protocol.model.LieDiceProtos.UserResultOrBuilder>(
                  openDiceUserResult_,
                  getParentForChildren(),
                  isClean());
          openDiceUserResult_ = null;
        }
        return openDiceUserResultBuilder_;
      }
      
      // required .game.UserResult callDiceUserResult = 2;
      private com.orange.network.game.protocol.model.LieDiceProtos.UserResult callDiceUserResult_ = com.orange.network.game.protocol.model.LieDiceProtos.UserResult.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.orange.network.game.protocol.model.LieDiceProtos.UserResult, com.orange.network.game.protocol.model.LieDiceProtos.UserResult.Builder, com.orange.network.game.protocol.model.LieDiceProtos.UserResultOrBuilder> callDiceUserResultBuilder_;
      public boolean hasCallDiceUserResult() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public com.orange.network.game.protocol.model.LieDiceProtos.UserResult getCallDiceUserResult() {
        if (callDiceUserResultBuilder_ == null) {
          return callDiceUserResult_;
        } else {
          return callDiceUserResultBuilder_.getMessage();
        }
      }
      public Builder setCallDiceUserResult(com.orange.network.game.protocol.model.LieDiceProtos.UserResult value) {
        if (callDiceUserResultBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          callDiceUserResult_ = value;
          onChanged();
        } else {
          callDiceUserResultBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder setCallDiceUserResult(
          com.orange.network.game.protocol.model.LieDiceProtos.UserResult.Builder builderForValue) {
        if (callDiceUserResultBuilder_ == null) {
          callDiceUserResult_ = builderForValue.build();
          onChanged();
        } else {
          callDiceUserResultBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder mergeCallDiceUserResult(com.orange.network.game.protocol.model.LieDiceProtos.UserResult value) {
        if (callDiceUserResultBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              callDiceUserResult_ != com.orange.network.game.protocol.model.LieDiceProtos.UserResult.getDefaultInstance()) {
            callDiceUserResult_ =
              com.orange.network.game.protocol.model.LieDiceProtos.UserResult.newBuilder(callDiceUserResult_).mergeFrom(value).buildPartial();
          } else {
            callDiceUserResult_ = value;
          }
          onChanged();
        } else {
          callDiceUserResultBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder clearCallDiceUserResult() {
        if (callDiceUserResultBuilder_ == null) {
          callDiceUserResult_ = com.orange.network.game.protocol.model.LieDiceProtos.UserResult.getDefaultInstance();
          onChanged();
        } else {
          callDiceUserResultBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      public com.orange.network.game.protocol.model.LieDiceProtos.UserResult.Builder getCallDiceUserResultBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getCallDiceUserResultFieldBuilder().getBuilder();
      }
      public com.orange.network.game.protocol.model.LieDiceProtos.UserResultOrBuilder getCallDiceUserResultOrBuilder() {
        if (callDiceUserResultBuilder_ != null) {
          return callDiceUserResultBuilder_.getMessageOrBuilder();
        } else {
          return callDiceUserResult_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          com.orange.network.game.protocol.model.LieDiceProtos.UserResult, com.orange.network.game.protocol.model.LieDiceProtos.UserResult.Builder, com.orange.network.game.protocol.model.LieDiceProtos.UserResultOrBuilder> 
          getCallDiceUserResultFieldBuilder() {
        if (callDiceUserResultBuilder_ == null) {
          callDiceUserResultBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.orange.network.game.protocol.model.LieDiceProtos.UserResult, com.orange.network.game.protocol.model.LieDiceProtos.UserResult.Builder, com.orange.network.game.protocol.model.LieDiceProtos.UserResultOrBuilder>(
                  callDiceUserResult_,
                  getParentForChildren(),
                  isClean());
          callDiceUserResult_ = null;
        }
        return callDiceUserResultBuilder_;
      }
      
      // optional int32 openType = 5 [default = 0];
      private int openType_ ;
      public boolean hasOpenType() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getOpenType() {
        return openType_;
      }
      public Builder setOpenType(int value) {
        bitField0_ |= 0x00000004;
        openType_ = value;
        onChanged();
        return this;
      }
      public Builder clearOpenType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        openType_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:game.LieDiceGameResult)
    }
    
    static {
      defaultInstance = new LieDiceGameResult(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:game.LieDiceGameResult)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_game_Dice_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_game_Dice_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_game_UserDice_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_game_UserDice_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_game_UserResult_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_game_UserResult_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_game_LieDiceGameResult_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_game_LieDiceGameResult_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rLieDice.proto\022\004game\032\017GameBasic.proto\"$" +
      "\n\004Dice\022\016\n\006diceId\030\001 \001(\005\022\014\n\004dice\030\002 \002(\005\"5\n\010" +
      "UserDice\022\016\n\006userId\030\001 \002(\005\022\031\n\005dices\030\002 \003(\0132" +
      "\n.game.Dice\"<\n\nUserResult\022\016\n\006userId\030\001 \002(" +
      "\t\022\013\n\003win\030\002 \002(\010\022\021\n\tgainCoins\030\005 \002(\005\"\204\001\n\021Li" +
      "eDiceGameResult\022,\n\022openDiceUserResult\030\001 " +
      "\002(\0132\020.game.UserResult\022,\n\022callDiceUserRes" +
      "ult\030\002 \002(\0132\020.game.UserResult\022\023\n\010openType\030" +
      "\005 \001(\005:\0010B7\n&com.orange.network.game.prot" +
      "ocol.modelB\rLieDiceProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_game_Dice_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_game_Dice_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_game_Dice_descriptor,
              new java.lang.String[] { "DiceId", "Dice", },
              com.orange.network.game.protocol.model.LieDiceProtos.Dice.class,
              com.orange.network.game.protocol.model.LieDiceProtos.Dice.Builder.class);
          internal_static_game_UserDice_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_game_UserDice_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_game_UserDice_descriptor,
              new java.lang.String[] { "UserId", "Dices", },
              com.orange.network.game.protocol.model.LieDiceProtos.UserDice.class,
              com.orange.network.game.protocol.model.LieDiceProtos.UserDice.Builder.class);
          internal_static_game_UserResult_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_game_UserResult_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_game_UserResult_descriptor,
              new java.lang.String[] { "UserId", "Win", "GainCoins", },
              com.orange.network.game.protocol.model.LieDiceProtos.UserResult.class,
              com.orange.network.game.protocol.model.LieDiceProtos.UserResult.Builder.class);
          internal_static_game_LieDiceGameResult_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_game_LieDiceGameResult_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_game_LieDiceGameResult_descriptor,
              new java.lang.String[] { "OpenDiceUserResult", "CallDiceUserResult", "OpenType", },
              com.orange.network.game.protocol.model.LieDiceProtos.LieDiceGameResult.class,
              com.orange.network.game.protocol.model.LieDiceProtos.LieDiceGameResult.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.orange.network.game.protocol.model.GameBasicProtos.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
